### ISSUE TITLE
The response parameter is missing.

### ISSUE THREAD

**Issue by srvsauravs** [CitroDigital/InvisibleRecpatcha#3]
When I drag the control in form builder and when I submit the form it says "The response parameter is missing."
Console error is below

Uncaught TypeError: recaptcha.execute is not a function
    at onRecaptchaLoad (<anonymous>:8:15)
    at <anonymous>:2:50

I have placed "@Html.RenderRecaptchaLib()" at the top in "_layout.cshtml"

**Comment by bpalmerzag** [comment]
I don't believe this is an issue with the product but more likely my misunderstanding on how to implement it. After installed and configuring, I've found the Kentico Form control available in the Form builder and placing it on the page results in a console error:

Uncaught ReferenceError: grecaptcha is not defined

Of course I need to: "Add following helper to _Layout.cshtml to load google script library"
@Html.RenderRecaptchaLib()

But when I add that, Visual Studio confirms there is an issue that I am not able to resolve by adding a using statement like:
@using CitroDigital.InvisibleRecaptcha;

The project builds but the _Layout.cshtml will bomb out with the following error:

**Compilation Error**
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS1061: 'HtmlHelper<BaseViewModel>' does not contain a definition for 'RenderRecaptchaLib' and no accessible extension method 'RenderRecaptchaLib' accepting a first argument of type 'HtmlHelper<BaseViewModel>' could be found (are you missing a using directive or an assembly reference?)

Can someone help me understand what I'm missing?
